apiVersion: v1
kind: Secret
metadata:
  name: civitrack-secrets
  namespace: civitrack
type: Opaque
stringData:
  jwt-secret: "civitrack_super_secret_key_change_in_production"
  auth-db-url: "postgresql://auth_user:auth_pass@auth-db-service:5432/auth_db"
  complaint-db-url: "postgresql://complaint_user:complaint_pass@complaint-db-service:5432/complaint_db"
  auth-db-password: "auth_pass"
  complaint-db-password: "complaint_pass"
